- feature_extractor:
    SiftExtraction.use_gpu: 1
    SiftExtraction.max_num_features: 4096
    ImageReader.camera_model: SIMPLE_RADIAL
    ImageReader.single_camera: 1
    ImageReader.single_camera_per_folder: 1

- sequential_matcher:
    SequentialMatching.vocab_tree_path: /tmp/vocab_tree.bin
    SiftMatching.use_gpu: 1
    SequentialMatching.overlap: 25
    
- transitive_matcher:
    TransitiveMatching.num_iterations: 10

- mapper:
    Mapper.multiple_models: 0

- model_aligner:
    ref_images_path: /tmp/georegistration.txt
    robust_alignment_max_error: 5

- image_undistorter:
    output_type: COLMAP

- patch_match_stereo:
    workspace_format: COLMAP
    PatchMatchStereo.geom_consistency: 1
    PatchMatchStereo.filter: 1
    PatchMatchStereo.max_image_size: 1000

- stereo_fusion:
    workspace_format: COLMAP
    input_type: geometric
    StereoFusion.max_image_size: 1000
