- feature_extractor:
    SiftExtraction.num_threads: 4
    SiftExtraction.use_gpu: 1
    SiftExtraction.max_num_features: 1024
    SiftExtraction.max_image_size: 500

- vocab_tree_matcher:
    VocabTreeMatching.vocab_tree_path: /home/jetson/vocab_tree.bin
    SiftMatching.use_gpu: 1
    SiftMatching.num_threads: 4
    VocabTreeMatching.num_images: 25 # default is 100
    VocabTreeMatching.num_checks: 64 # default is 256
    
- hierarchical_mapper:
    Mapper.ignore_watermarks: 1
    Mapper.max_num_models: 25

- image_undistorter:
    max_image_size: 500
    output_type: COLMAP

- patch_match_stereo:
    workspace_format: COLMAP
    PatchMatchStereo.window_step: 2 # default is 1
    PatchMatchStereo.window_radius: 4 # default is 5
    PatchMatchStereo.geom_consistency: 1
    PatchMatchStereo.filter: 1
    PatchMatchStereo.max_image_size: 500
    PatchMatchStereo.num_iterations: 4 # default is 5
    PatchMatchStereo.num_samples: 10 # default is 15

- stereo_fusion:
    workspace_format: COLMAP
    input_type: geometric
    StereoFusion.max_image_size: 500
    

    
